<?php

return [
	'mode'                          => 'utf-8',
	'format'                        => 'A4',
	'author'                        => '',
	'subject'                       => '',
	'keywords'                      => '',
	'creator'                       => 'Laravel Pdf',
	'display_mode'                  => 'fullpage',
	'tempDir'                       => base_path('../temp/'),
	'pdf_a'                         => false,
	'pdf_a_auto'                    => false,
	'icc_profile_path'              => '',
    'default_font_size'             => '12',
    'default_font'                  => 'sans-serif',
    'margin_left'                   => 10,
    'margin_right'                  => 10,
    'margin_top'                    => 10,
    'margin_bottom'                 => 10,
    'margin_header'                 => 0,
    'margin_footer'                 => 0,
    'orientation'                   => 'P',
    'title'                         => 'Laravel mPDF',
    'watermark'                     => '',
    'show_watermark'                => false,
    'show_watermark_image'          => false,
    'watermark_font'                => 'sans-serif',
    'watermark_text_alpha'          => 0.1,
    'watermark_image_path'          => '',
    'watermark_image_alpha'         => 0.2,
    'watermark_image_size'          => 'D',
    'watermark_image_position'      => 'P',
    'custom_font_dir'               => '',
    'custom_font_data'              => [],
    'auto_language_detection'       => false,
    // 'temp_dir'                      => rtrim(sys_get_temp_dir(), DIRECTORY_SEPARATOR),
    'temp_dir'                      => base_path('storage/app/pdf/'),
    'pdfa'                          => false,
    'pdfaauto'                      => false,
    'use_active_forms'              => false,
];
